---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
version: "1.0"

generics:
  - name: Generic
    namespace: Service
    description: Generic service...
    label: Service
    icon: mdi:package-variant
    include_in_menu: true
    human_friendly_id:
      - service_identifier__value
    order_by:
      - service_identifier__value
    display_labels:
      - service_identifier__value
    attributes:
      - name: service_identifier
        kind: Text
        unique: true
        order_weight: 1000
        optional: false
      - name: account_reference
        kind: Text
        order_weight: 1000
        optional: false

nodes:
  - name: DedicatedInternet
    namespace: Service
    description: This service provides customers with a dedicated physical port, ensuring complete internet connectivity.
    label: Dedicated Internet
    icon: mdi:ethernet
    menu_placement: ServiceGeneric
    inherit_from:
      - ServiceGeneric
    include_in_menu: true
    attributes:
      - name: bandwidth
        kind: Dropdown
        optional: false
        default_value: "1000"
        order_weight: 1100
        choices:
          - name: "100"
            label: Hundred Megabits
            description: Provides a 100 Mbps bandwidth.
          - name: "1000"
            label: One Gigabit
            description: Provides a 1 Gbps bandwidth.
          - name: "10000"
            label: Ten Gigabits
            description: Provides a 10 Gbps bandwidth.
      - name: ip_package
        kind: Dropdown
        optional: false
        order_weight: 1120
        default_value: small
        choices:
          - name: small
            label: Small
            description: Provide customer with 6 IPs.
            color: "#6a5acd"
          - name: medium
            label: Medium
            description: Provide customer with 14 IPs.
            color: "#9090de"
          - name: large
            label: Large
            description: Provide customer with 30 IPs.
            color: "#ffa07a"
    relationships:
      - name: location
        peer: LocationSite
        order_weight: 1150
        cardinality: one
        direction: inbound
        identifier: service_site
        optional: false
      - name: dedicated_interfaces
        peer: DcimInterface
        kind: Attribute
        order_weight: 1200
        cardinality: many
        direction: inbound
        identifier: service_interface
      - name: vlan
        peer: IpamVLAN
        kind: Attribute
        order_weight: 1300
        cardinality: one
        direction: inbound
        identifier: service_vlan
      - name: gateway_ip_address
        peer: IpamIPAddress
        order_weight: 1350
        cardinality: one
        direction: inbound
        identifier: service_ip_address
      - name: prefix
        peer: IpamPrefix
        kind: Attribute
        order_weight: 1400
        cardinality: one
        direction: inbound
        identifier: service_prefix

extensions:
  nodes:
    - kind: LocationSite
      relationships:
        - name: services
          peer: ServiceGeneric
          cardinality: many
          direction: outbound
          identifier: service_site
    - kind: DcimInterface
      relationships:
        - name: service
          peer: ServiceGeneric
          cardinality: one
          direction: outbound
          identifier: service_interface
    - kind: IpamVLAN
      relationships:
        - name: service
          peer: ServiceGeneric
          cardinality: one
          direction: outbound
          identifier: service_vlan
    - kind: IpamIPAddress
      relationships:
        - name: service
          peer: ServiceGeneric
          cardinality: one
          direction: outbound
          identifier: service_ip_address
    - kind: IpamPrefix
      relationships:
        - name: service
          peer: ServiceGeneric
          cardinality: one
          direction: outbound
          identifier: service_prefix
