# yaml-language-server: $schema=https://schema.infrahub.app/python-sdk/repository-config/latest.json
---
# GENERATORS
generator_definitions:
  - name: dedicated_internet_generator
    file_path: "generators/implement_dedicated_internet.py"
    targets: automated_dedicated_internet
    query: dedicated-internet-info
    class_name: DedicatedInternetGenerator
    parameters:
      service_identifier: "service_identifier__value"

# QUERIES
queries:
  - name: dedicated-internet-info
    file_path: "generators/dedicated_internet.gql"
  - name: device_info
    file_path: "templates/device_info.gql"

# SCHEMAS
schemas:
  - schemas/base
  - schemas/location_minimal
  - schemas/vlan
  - schemas/service

# TRANSFORMS
jinja2_transforms:
  - name: device_config
    description: Template to generate startup configuration for devices
    query: device_info
    template_path: "templates/device_config.j2"

# ARTIFACTS
artifact_definitions:
  - name: Startup Config
    artifact_name: startup-config
    parameters:
      device_name: name__value
    content_type: text/plain
    targets: generic_devices
    transformation: device_config
