# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/menu/latest.json
---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    - namespace: Location
      name: Menu
      label: Location
      kind: LocationGeneric
      icon: "mingcute:location-line"
      children:
        data:
          - namespace: Location
            name: Generic
            label: All Locations
            kind: LocationGeneric
            icon: "mingcute:location-line"

          - namespace: Location
            name: Country
            label: Country
            kind: LocationCountry
            icon: "gis:search-country"

          - namespace: Location
            name: Metro
            label: Metro
            kind: LocationMetro
            icon: "healthicons:city"

          - namespace: Location
            name: Site
            label: Site
            kind: LocationSite
            icon: "ri:building-line"

          - namespace: Location
            name: Rack
            label: Rack
            kind: LocationRack
            icon: clarity:rack-server-solid

    - namespace: Dcim
      name: DeviceManagementMenu
      label: Device Management
      icon: "mdi:server"
      children:
        data:
          - namespace: Dcim
            name: NetworkDeviceMenu
            label: Network Device
            icon: "mdi:server"
            children:
              data:
                - namespace: Dcim
                  name: Device
                  label: Device
                  kind: DcimDevice
                  icon: "mdi:server"
                - name: Interface
                  namespace: Dcim
                  label: "Interface"
                  icon: "mdi:ethernet"
                  kind: DcimInterface

          - namespace: Infra
            name: MlagMenu
            label: MLAG
            icon: "eos-icons:cluster-management"
            children:
              data:
                - name: MlagDomain
                  namespace: Infra
                  label: "MLAG Domain"
                  icon: "eos-icons:cluster-management"
                  kind: InfraMlagDomain

                - name: MlagInterface
                  namespace: Infra
                  label: "MLAG Interface"
                  icon: "mdi:ethernet"
                  kind: InfraMlagInterface

          - namespace: Infra
            name: Platform
            label: Platform
            kind: InfraPlatform
            icon: "mdi:application-cog-outline"

    - namespace: Infra
      name: Service
      label: Services
      icon: "carbon:container-services"
      children:
        data:
          - namespace: Infra
            name: BackBoneService
            label: "Backbone Service"
            kind: InfraBackBoneService
            icon: "carbon:container-services"
