#
# Protocol definitions for Infrahub generators
# These are duplicated here to allow generators to run within Infrahub's
# environment without requiring the service_catalog package to be installed.
#
# Generated by "infrahubctl protocols" and trimmed to only include types
# needed by the generators.
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreArtifactTarget,
    CoreNode,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        BooleanOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPNetwork,
        String,
        StringOptional,
    )


class DcimGenericDevice(CoreNode):
    description: StringOptional
    name: String
    os_version: StringOptional
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimPhysicalDevice(CoreNode):
    position: IntegerOptional
    rack_face: DropdownOptional
    serial: StringOptional
    device_type: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimEndpoint(CoreNode):
    connector: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimInterface(CoreNode):
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    speed: Integer
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceGeneric(CoreNode):
    account_reference: String
    service_identifier: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimDevice(CoreArtifactTarget, DcimGenericDevice, DcimPhysicalDevice):
    description: StringOptional
    index: IntegerOptional
    name: String
    os_version: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    status: Dropdown
    artifacts: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    object_template: RelatedNode
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimInterfaceL2(DcimInterface, DcimEndpoint):
    description: StringOptional
    enabled: BooleanOptional
    l2_mode: StringOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    speed: Integer
    status: DropdownOptional
    connector: RelatedNode
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tagged_vlan: RelationshipManager
    tags: RelationshipManager
    untagged_vlan: RelatedNode


class DcimInterfaceL3(DcimInterface, DcimEndpoint):
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    speed: Integer
    status: DropdownOptional
    connector: RelatedNode
    device: RelatedNode
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class IpamIPAddress(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    fqdn: StringOptional
    interface: RelatedNode
    ip_namespace: RelatedNode
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager


class IpamPrefix(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: BooleanOptional
    is_top_level: BooleanOptional
    member_type: DropdownOptional
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    role: DropdownOptional
    status: Dropdown
    utilization: IntegerOptional
    children: RelationshipManager
    gateway: RelatedNode
    ip_addresses: RelationshipManager
    ip_namespace: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    organization: RelatedNode
    parent: RelatedNode
    profiles: RelationshipManager
    resource_pool: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    vlan: RelatedNode


class IpamVLAN(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    vlan_id: Integer
    l2domain: RelatedNode
    location: RelationshipManager
    member_of_groups: RelationshipManager
    prefixes: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager


class ServiceDedicatedInternet(ServiceGeneric):
    account_reference: String
    bandwidth: Dropdown
    ip_package: Dropdown
    service_identifier: String
    status: DropdownOptional
    dedicated_interfaces: RelationshipManager
    gateway_ip_address: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    prefix: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    vlan: RelatedNode
